### ISSUE TITLE
Value of "is_enabled" alert parameter is ignored

### ISSUE THREAD

**Issue by jakubmasa-massive** [logzio/terraform_provider_logzio#47]
When creating or updating alert, value set to "is_enabled" parameter is ignored and alert is always enabled (default "true" value is used).

How to reproduce (create alert):

- Create a sample alert:
```
resource "logzio_alert" "hello_world" {
  title = "hello_world"
  query_string = "level:ERROR"
  operation = "GREATER_THAN"
  notification_emails = ["some@email.com"]
  search_timeframe_minutes = 5
  value_aggregation_type = "NONE"
  alert_notification_endpoints = []
  suppress_notifications_minutes = 5
  severity_threshold_tiers {
      severity = "HIGH"
      threshold = 10
  }
  filter = "{\"bool\":{\"must\":[],\"should\":[],\"filter\":[],\"must_not\":[]}}"
  is_enabled = false
} 
```
 - Observe that alert is enabled in logzio

If I manually disable alert and do any update in the sample, but leaving "is_enabled = false", alert will be reactivated.

I did not find a cause of this bug. I was thinking using [GetOkExists](https://godoc.org/github.com/hashicorp/terraform/helper/schema#ResourceData.GetOkExists) to read is_enabled schema value instead of [GetOk](https://godoc.org/github.com/hashicorp/terraform/helper/schema#ResourceData.GetOk) but that did not fix the issue from my testing.

I would appreciate any help to fix this.

**Comment by yyyogev** [comment]
@jakubmasa-massive thanks for letting us know. We will handle it soon

**Comment by yyyogev** [comment]
Fixed at https://github.com/logzio/terraform_provider_logzio/pull/50
@jakubmasa-massive thanks
