### ISSUE TITLE
Provider dose not support import subaccout 

### ISSUE THREAD

**Issue by davidriskified** [logzio/terraform_provider_logzio#48]
terraform import module.sub_accounts.logzio_subaccount.test 22345
Acquiring state lock. This may take a few moments...
module.sub_accounts.logzio_subaccount.test: Importing from ID "22345"...

Error: resource logzio_subaccount doesn't support import

Releasing state lock. This may take a few moments...

**Comment by yyyogev** [comment]
Can you explain exactly what were you trying to do? and could you please share your main.tf file?
Thanks

**Comment by davidriskified** [comment]
`terraform import logzio_subaccount.loadtest 29640`

**Comment by davidriskified** [comment]
Hi @yyyogev 
I was able to fix this issue :-)
Under file **resource_subaccount.go** add the following:
```
func resourceSubAccount() *schema.Resource {
	return &schema.Resource{
		Create: resourceSubAccountCreate,
		Read:   resourceSubAccountRead,
		Update: resourceSubAccountUpdate,
		Delete: resourceSubAccountDelete,
		Importer: &schema.ResourceImporter{             <-------------- HERE ----------------
			State: schema.ImportStatePassthrough,   <-------------- HERE ----------------
		},                                              <-------------- HERE ----------------
```

I strongly suggest to add importer to each resource 
See guide lines and best practices for that under the following links:
https://www.terraform.io/docs/extend/resources/import.html
https://learn.hashicorp.com/tutorials/terraform/state-import

**Comment by yyyogev** [comment]
Hi @davidriskified, thanks a lot for your suggestion.
This one might take a little longer since we first focusing on bug fixes and only then addressing feature requests.
You are more than welcome to help and contribute to this project by forking this repo, add your contribution to a side branch, and issue a PR.
Thanks!

**Comment by davidriskified** [comment]
Hi @yyyogev the solution is already there just copy an pasted it to the other resources

**Comment by yyyogev** [comment]
I see. I'll try to push it forward then.
Thanks again!

**Comment by yyyogev** [comment]
Done https://github.com/logzio/terraform_provider_logzio/pull/50
@davidriskified thanks
